### ISSUE TITLE
Stopped decoding SAML Messages

### ISSUE THREAD

**Issue by RussellFord** [magnussuther/saml-message-decoder-extension#4]
This extension worked GREAT for the first few weeks that I used it. After a while though the extension stopped decoding SAML messages. At first I thought there was something wrong with my IDP implementation and the way the SAML message was being generated, but after checking several times, I cannot find anything that changed in my implementation. I've even tried other SAML IDPs that previously worked to no avail.

**Comment by Ramexises** [comment]
Has also stopped for me in the last 24 hrs. No SAML Traces being logged.
Could be to do with Chrome update!
I restarted my PC after being on for a while yesterday and Chrome has slightly different settings menu hierarchy.
